### ISSUE TITLE
Add an "Angular friendly" way to compress/minify Angular app/source files

### ISSUE THREAD

**Issue by sharissis-brei** [BarkleyREI/generator-brei-app#101]

**Comment by nessthehero** [comment]
Since @Sean-BREI was able to compress Angular things for NOVA, we may just need to compare your code and his to see if there is any real reason why compressing it fails.

I almost wonder if the "uglify" part of the compression is breaking it, since I think uglify renames variables to single characters in order to save space.

**Comment by dtm5011** [comment]
Minifying breaks Angular's dependency injection because it's interpreting the params as strings.

The most common solution to this is to add [ng-annotate](https://github.com/olov/ng-annotate) to your build step.

**Comment by nessthehero** [comment]
I'll look into ng-annotate, but to make that work we'll likely need to set up a common structure for angular stuff in our projects, so that it can be properly targeted.

**Comment by Sean-BREI** [comment]
I'll work on creating a common boilerplate project that can be dropped into the generator - i.e. default JS files, directory architecture, and etc.

**Comment by nessthehero** [comment]
Angular is illegal now and anyone who writes it goes straight to jail.
