### ISSUE TITLE
Add Inquire.js prompting to enable/disable features

### ISSUE THREAD

**Issue by nessthehero** [BarkleyREI/generator-brei-app#23]
This is the prompting that is seen on line 20 in app/index.js.

I want to add checkboxes to enable/disable features like SASS, Assemble, (eventually) Require.js, etc.

The reason I see this as important is I never want to force a current or future developer to HAVE to use this stuff right off the bat. They should be able to remove requirements such as the assemble stuff or SASS from the project and have everything still work just the same. I think it is important so I plan on adding it to the generator regardless.

**Comment by JDillon522** [comment]
So I think we need a better game plan for this one. As for myself, I have no problem (and actually recommend) forcing future developers to use a set of tools that everyone else is using. That makes working as a team a hell of a lot better and more efficient (yay conventions). 

However, if we do want to give options (like LESS vs SASS vs Stylus, etc) than we need to write in those options. Take a look at the [generator for express.js projects](http://expressjs.com/starter/generator.html). They provide a number of configuration options but they default to a certain set. 

Writing all the agreed upon options, everything that goes with them, and then their corresponding tests would require a shit ton of work. 

Although it I'm not the biggest fan of providing felxiblity, I still think it would be cool to build options. But this level of change is a 3.0.0 change due to the extreme rewrite.

**Comment by nessthehero** [comment]
At this point we're probably all on board with everything we're using, so I'm fine with it. We will just need to include things like READMEs and documentation on how to use all this junk so that nobody is ever confused.
