### ISSUE TITLE
Add random messages to the .scss file after it's generated

### ISSUE THREAD

**Issue by eightdotthree** [BarkleyREI/generator-brei-app#38]

**Comment by JDillon522** [comment]
So its a little hard to see when it runs because there are a lot of other things running on top of it, but here are the current messages that it does spit out:

>'Updating Assemble.io sass...'

>'A SASS file doesnt exist. "I can fix it!" - Fix-it-Felix jr.'

>'I just wrote <name> for you!'

and 

>'Done! <name> updated!'

Eventually I think I might make it an actual grunt module so that it has its own organized output.  But thats a story for a different day.
